-- Create Users table (linked to Auth)
create table public.users (
  id uuid references auth.users not null primary key,
  username text,
  phone_number text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for Users
alter table public.users enable row level security;

-- Create Policy: Users can read their own data (or everyone's if you want public profiles)
create policy "Public profiles are viewable by everyone."
  on public.users for select
  using ( true );

create policy "Users can insert their own profile."
  on public.users for insert
  with check ( auth.uid() = id );

create policy "Users can update their own profile."
  on public.users for update
  using ( auth.uid() = id );

-- Create Messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  room_id text not null,
  user_id uuid references public.users(id),
  username text,
  message text,
  created_at bigint not null -- Storing as number (timestamp) match existing logic
);

-- Enable RLS for Messages
alter table public.messages enable row level security;

-- Create Policy: Anyone can read messages
create policy "Messages are viewable by everyone."
  on public.messages for select
  using ( true );

-- Create Policy: Authenticated users can insert messages
create policy "Authenticated users can insert messages."
  on public.messages for insert
  with check ( auth.role() = 'authenticated' );
